events {}

http{
    server{
        listen 8080;

        location /items/{
            proxy_pass http://item-service:8081/;
        }
        location /orders/{
            proxy_pass http://order-service:8082/;
        }
        location /payments/{
            proxy_pass http://payment-service:8083/;
        }
    }
}