version: "3.8"

services:
  item-service:
    build: ./item-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    networks:
      - microservices-net

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
    networks:
      - microservices-net

  payment-service:
    build: ./payment-service
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
    networks:
      - microservices-net

  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - item-service
      - order-service
      - payment-service
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge